// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: konvik.proto

package konvik_proto_describe

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KonvikClient is the client API for Konvik service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KonvikClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type konvikClient struct {
	cc grpc.ClientConnInterface
}

func NewKonvikClient(cc grpc.ClientConnInterface) KonvikClient {
	return &konvikClient{cc}
}

func (c *konvikClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/konvik.Konvik/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KonvikServer is the server API for Konvik service.
// All implementations must embed UnimplementedKonvikServer
// for forward compatibility
type KonvikServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedKonvikServer()
}

// UnimplementedKonvikServer must be embedded to have forward compatible implementations.
type UnimplementedKonvikServer struct {
}

func (UnimplementedKonvikServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedKonvikServer) mustEmbedUnimplementedKonvikServer() {}

// UnsafeKonvikServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KonvikServer will
// result in compilation errors.
type UnsafeKonvikServer interface {
	mustEmbedUnimplementedKonvikServer()
}

func RegisterKonvikServer(s grpc.ServiceRegistrar, srv KonvikServer) {
	s.RegisterService(&Konvik_ServiceDesc, srv)
}

func _Konvik_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KonvikServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/konvik.Konvik/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KonvikServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Konvik_ServiceDesc is the grpc.ServiceDesc for Konvik service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Konvik_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "konvik.Konvik",
	HandlerType: (*KonvikServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Konvik_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "konvik.proto",
}
